= ZEN

XR Desktop Environment

== Build & Install

=== Dependencies

. wlr-glew-renderer +
Please see https://github.com/zigen-project/wlr-glew-renderer[zigen-project/wlr-glew-renderer]
to build and install.
. zen-remote +
Please see https://github.com/zigen-project/zen-remote[zigen-project/zen-remote]
to build and install.
. tomlc99 +
Please see https://github.com/cktan/tomlc99[cktan/tomlc99] to build and install. +
Note that `make install` tries to install `libtoml.pc` to `/usr/local/lib/pkgconfig`.
You need to rename `libtoml.pc.sample` in the tomlc99 project root to `libtoml.pc`
and manually create `/usr/local/lib/pkgconfig` before running `make install`.
. cglm +
Please see https://github.com/recp/cglm[recp/cglm] and install cglm of the
version listed in `meson.build`. Basically, the latest version is fine.
. Other dependencies +
For Ubuntu, other dependencies can be installed with `apt-get`.
See `.github/workflows/test.yaml` and `meson.build` for the list of the
required packages.

=== Build & Install

[source, shell]
----
$ git clone https://github.com/zigen-project/zen.git
$ cd zen
$ meson build
$ ninja -C build install
----

== Start ZEN Desktop

=== Option 1

Select `ZEN` from your display manager.

=== Option 2

[red]#***__caution__**# +
Switching between virtual terminals may be confusing if you are not familiar
with it. You may not be able to return to your GUI desktop except by forced
reboot.

- Switch virtual terminal

[source, shell]
----
$ sudo chvt <number>
----

- In a virtual terminal (CUI),

[source, shell]
----
$ zen-desktop
----

== Key bindings

We cannot customize these bindings for now.

.Key bindings
[%autowidth.stretch]
|===
|bindings|description

|<mod> + <shift> + →
|Move to next board

|<mod> + <shift> + ←
|Move to previous board

|<mod> + <shift> + n
|Create new board

|<alt> + q
|Terminate ZEN Desktop (for development convenience)

|===
