= ZEN

XR Desktop Environment

== Build & Install

=== Dependencies

1. wlr-glew-renderer +
See https://github.com/zigen-project/wlr-glew-renderer[github.com/zigen-project/wlr-glew-renderer] to build and install.
2. tomlc99 +
See https://github.com/cktan/tomlc99[cktan/tomlc99] to build and install. +
Note that `make install` tries to install `libtoml.pc` under `/usr/local/lib/pkgconfig`. You need to manually create the directory before runnning `make`.
3. Other dependencies +
For Ubuntu, other dependencies can be installed with `apt-get`. See `.github/workflows/test.yaml` for the list of the required packages.

=== Build & Install

[source, shell]
----
$ git clone https://github.com/zigen-project/zen.git
$ cd zen
$ meson build
$ ninja -C build install
----

== Start ZEN Desktop

=== Option 1

Select `ZEN` from your display manager.

=== Option 2

[red]#***__caution__**# +
Switching between virtual terminals may be confusing if you are not familiar
with it. You may not be able to return to your GUI desktop except by forced
reboot.

- Switch virtual terminal

```
$ sudo chvt <number>
```

- In a virtual terminal (CUI),

```
$ zen-desktop
```

== Key bindings

We cannot customize these bindings for now.

.Key bindings
[%autowidth.stretch]
|===
|bindings|description

|<mod> + <shift> + →
|Move to next board

|<mod> + <shift> + ←
|Move to previous board

|<mod> + <shift> + n
|Create new board

|<alt> + q
|Terminate ZEN Desktop (for development convenience)

|===
