= ZEN

XR Desktop Environment

== Build & Install

=== Dependencies

. zwin protocols +
Please see https://github.com/zwin-project/zwin[zwin-project/zwin]
to build and install. +
[yellow]#***__important__**#: Please use `draft` branch.
. zen-remote +
Please see https://github.com/zwin-project/zen-remote[zwin-project/zen-remote]
to build and install.
. Other dependencies +
For Ubuntu, other dependencies can be installed with `apt-get`.
See `.github/workflows/test.yaml` and `meson.build` for the list of the
required packages.

=== Build & Install

[source, shell]
----
$ git clone https://github.com/zwin-project/zen.git
$ cd zen
$ meson build
$ ninja -C build install
----

== Start ZEN Desktop

=== Option 1

Select `ZEN` from your display manager.

=== Option 2

[red]#***__caution__**# +
Switching between virtual terminals may be confusing if you are not familiar
with it. You may not be able to return to your GUI desktop except by forced
reboot.

- Switch virtual terminal

[source, shell]
----
$ sudo chvt <number>
----

- In a virtual terminal (CUI),

[source, shell]
----
$ zen-desktop
----

== Key bindings

We cannot customize these bindings for now.

.Key bindings
[%autowidth.stretch]
|===
|bindings|description

|<mod> + <shift> + →
|Move to next board

|<mod> + <shift> + ←
|Move to previous board

|<alt> + q
|Terminate ZEN Desktop (for development convenience)

|===
